site_name: A Step Toward World Modelsï¼š A Survey on Robotic Manipulation
theme:
  name: material
  features:
    - navigation.tabs         # â† æ–°å¢ï¼šé¡¶æ  Tab
    - navigation.tabs.sticky  # â† å¯é€‰ï¼šæ»šåŠ¨æ—¶å¸é¡¶
    - toc.integrate
    - navigation.sections
    - header.autohide

# è®© Markdown ç”Ÿæˆå¯ç‚¹å‡»çš„é”šç‚¹ï¼Œå¹¶æ§åˆ¶ TOC æ˜¾ç¤ºå±‚çº§
markdown_extensions:
  - pymdownx.arithmatex 
  - toc:
      permalink: true      # æ ‡é¢˜å³ä¾§å‡ºç°ğŸ”—é”šç‚¹
      toc_depth: "2-3"     # åœ¨ä¾§è¾¹æ æ˜¾ç¤º h2~h3ï¼ˆå¯æŒ‰éœ€æ”¹æˆ "2-4"ï¼‰
  - attr_list     # å…è®¸ {...} å±æ€§
  - md_in_html    # å…è®¸åœ¨ Markdown é‡Œå†™å°‘é‡ HTML
  - footnotes

plugins:
  - search
  - bibtex:
      bib_file: docs/refs.bib        # ä½ çš„ BibTeX æ–‡ä»¶
      csl_file: docs/ieee.csl   


extra_javascript:
  - js/strip-nocase.js

nav:
  - About:
      - Abstract: index.md
      - I Introduction: 01-introduction.md
      - II Preliminaries: 02-preliminaries.md
      - III Overview of the World Model: 03-overview.md
      - IV Functions of the World Model: 04-functions.md
      - V Key Techniques and Notable Challenges: 05-key-tech-challenges.md
      - VI Core Components & Capabilities: 06-core-components.md
      - VII Dataset: 07-dataset.md
      - VIII Conclusion & Future directions: 08-conclusion.md
  # - Paper and Codes: contact.md
  # - About: about.md
  - Reference Collection: 99-references.md